%%{init: {"theme": "default", "themeVariables": { "fontSize": "20px", "primaryColor": "#E0F2FE", "edgeLabelBackground":"#ffffff"}}}%%
flowchart TD

  A["📨 HTTP Client<br/>(POST /upload,<br/>GET /meals,<br/>Get /meal-image)"]:::client
  Y["🛰️ API Gateway"]:::apigw

  %% Write Plane
  subgraph WRITE["✍️ Write Plane 🔐"]
    B["📡 Lambda API -<br/>Upload Handler"]:::lambda
    C["📦 Amazon S3"]:::s3
    D["🧩 EventBridge<br/>(From S3 Upload)"]:::event
    E["🧩 EventBridge<br/>(Triggers DB Handler)"]:::event
    F["📡 Lambda<br/>DynamoDB Handler"]:::lambda
    G["🗃️ DynamoDB Meals<br/>Table (with likes)"]:::ddb
    H["🔎 Lambda<br/>OpenSearch Indexer"]:::lambda
  end

  %% Read Plane
  subgraph READ["📖 Read Plane"]
    R1["📡 Lambda API -<br/>Get Meals Handler"]:::lambda
    R2["🔎 OpenSearch<br/>(Indexed Meals)"]:::search

    R3["📡 Lambda API -<br/>Get Meal Image"]:::lambda
    R4["🗃️ DynamoDB Meals<br/>Table (with likes)"]:::ddb
    R5["📦 Amazon S3"]:::s3
  end

  %% Client routes
  A -->|🔐 Auth Context -<br/>Only For Write| Y
  Y -->|Upload Multipart Form| B
  Y -->|Read Query| R1
  Y -->|Meal Image Query| R3
  R1 -->|Get Meals| R2
  R3 -->|Get Image URL| R4
  R4 -->|Stream Image| R5

  %% Write flow
  B -->|Store Image| C
  C -->|Publish Event| D
  E -->|Meal Uploaded Event| F
  F -->|Insert Record| G
  G -->|DynamoDB Stream<br/>Event| H

  %% Class styles
  classDef client fill:#F0F9FF,stroke:#0284C7,color:#075985;
  classDef apigw fill:#E0F2FE,stroke:#06B6D4,color:#0F172A;
  classDef lambda fill:#E0F2FE,stroke:#0EA5E9,color:#1E3A8A;
  classDef s3 fill:#FEF9C3,stroke:#CA8A04,color:#78350F;
  classDef event fill:#DDD6FE,stroke:#8B5CF6,color:#4C1D95;
  classDef ddb fill:#BBF7D0,stroke:#22C55E,color:#14532D;
  classDef search fill:#F3E8FF,stroke:#A855F7,color:#6B21A8;

  linkStyle default stroke-width:2px,fill:none;
